/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    System.out.print("Ingrese el valor:");
    int value = scanner.nextInt();
    Game game = new Game(value);
    scanner.close();
    game.setVisible(true);
  }
}
